export enum FunctionalE2ETestsEnum {
    SHOULD_AWAIT_FOR_INDICATORS_TO_SHOW = 'SHOULD_AWAIT_FOR_INDICATORS_TO_SHOW',
    SHOULD_PRESENT_PROPER_RESULTS_AFTER_NTH_CLICK = 'SHOULD_PRESENT_PROPER_RESULTS_AFTER_NTH_CLICK'
}