export const WIDGET_VERTICAL_PERCENTAGE_CONTROL_DATA_TEST_LABELS = {
  WIDGET_VERTICAL_PERCENTAGE_CONTROL_DATA_TEST_PLUS_BUTTON:
    'WIDGET_VERTICAL_PERCENTAGE_CONTROL_DATA_TEST_PLUS_BUTTON',
  WIDGET_VERTICAL_PERCENTAGE_CONTROL_DATA_TEST_MINUS_BUTTON:
    'WIDGET_VERTICAL_PERCENTAGE_CONTROL_DATA_TEST_MINUS_BUTTON',
  WIDGET_VERTICAL_PERCENTAGE_CONTROL_DATA_TEST_RESULT:
    'WIDGET_VERTICAL_PERCENTAGE_CONTROL_DATA_TEST_RESULT',
} as const;
