export const BATTERY_DATA_TEST_IDS = {
  BATTERY_TIME_LEFT_WRAPPER: 'BATTERY_TIME_LEFT_WRAPPER',
  BATTERY_ICON_WRAPPER: 'BATTERY_ICON_WRAPPER',
  BATTERY_ICON: 'BATTERY_ICON',
  BATTERY_TEXT_LABEL: 'BATTERY_TEXT_LABEL',
  BATTERY_EFFECTIVE_TIME_LEFT: 'BATTERY_EFFECTIVE_TIME_LEFT',
} as const;
