name: Test and Deploy to Staging

on:
  workflow_dispatch:

  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  test:
    uses: ./.github/workflows/test.common.yml
    with:
      run_production_tests: false
  build-and-deploy:
    name: Build and Deploy to Staging
    needs:
      - test
    uses: ./.github/workflows/deploy.common.yml
    with:
      ssh_destination_dir: ${{  vars.STAGING_DESTINATION }}
      ssh_deployment_url: ${{ vars.STAGING_DOMAIN_NAME }}    
    secrets: inherit


