name: Test and Deploy to Production

on:
  workflow_dispatch:

  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  test:
    uses: ./.github/workflows/test.common.yml
    with:
      run_production_tests: true
  build-and-deploy:
    name: Build and Deploy to Production
    needs:
      - test
    uses: ./.github/workflows/deploy.common.yml
    with:
      ssh_destination_dir: ${{ vars.PRODUCTION_DESTINATION }}
      ssh_deployment_url: ${{ vars.PRODUCTION_DOMAIN_NAME }}
    secrets: inherit
